### ISSUE TITLE
Race condition in Dump.Exec

### ISSUE THREAD

**Issue by retanik** [habx/pg-commands#53]
I encountered a race condition detected from go test and after reviewing  your CircleCI Orb i see you have it turned off. It might be worth enabling it to catch those cases. 

Orb Source line 312+
```
- go/test:
                covermode: atomic
                coverprofile: coverage.out
                failfast: true
                race: false
                verbose: true
```

Race condition was encountered between
```
Read at 0x00c0003fc020 by goroutine 67:
  github.com/habx/pg-commands.(*Dump).Exec()
      /x/x/go/pkg/mod/github.com/habx/pg-commands@v0.6.1/pg_dump.go:64 +0xb16
```
and 
```
Previous write at 0x00c0003fc020 by goroutine 68:
  github.com/habx/pg-commands.streamOutput()
      /x/x/go/pkg/mod/github.com/habx/pg-commands@v0.6.1/utils.go:45 +0x1d3
  github.com/habx/pg-commands.(*Dump).Exec.func1()
      /x/x/go/pkg/mod/github.com/habx/pg-commands@v0.6.1/pg_dump.go:54 +0x8a
```

I was running a unit test which uses suite.run to sequentially trigger multiple database exports. In Exec the streamOutput function is started as a go routine and can not be observed from outside to know when it has finished. I believe that is where the race condition occurs as it is unmanaged writing and reading from the Result.Error variable in both routines
